title: Rebecca Badman Typogblog
description: A typography blog
header_text: The Typog-Blog
footer_text: Copyright 2020 Bex Badman
header_feature_image: ../uploads/d9515bbe-b44d-46f8-9d13-f12d6ed6ed4c.jpeg
bannerheight: 20vmax
logo: ../uploads/a0cfbc51-da56-42a7-91e3-c7e57d76e425_1_201_a.jpeg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
