title: The Little Ladies Blog
description: "A blog surrounding typography "
header_text: Back to Font
footer_text: Copyright 2020 Bex Badman
header_feature_image: ../uploads/untitled-2.png
bannerheight: 20vmax
logo: ../uploads/a0cfbc51-da56-42a7-91e3-c7e57d76e425_1_201_a.jpeg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
