title: The Little Ladies Blog
description: "A blog surrounding typography "
header_text: Back to Font
footer_text: Copyright 2020 Bex Badman
header_feature_image: ../uploads/untitled-2.png
bannerheight: 20vmax
logo: ../uploads/favicon.png
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: false
upzoom: true
