title: The Little Ladies Blog
description: A blog surrounding typography with a feminist twist
header_text: ""
footer_text: Copyright 2020 Bex Badman
header_feature_image: ../uploads/untitled-2.png
bannerheight: 20vmax
logo: ../uploads/favicon.png
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
items:
  - name: About Bex Badman
    siteurl: /aboutme
    tab: true
